# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'git_and_circles.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Circles(object):
    def setupUi(self, Circles):
        Circles.setObjectName("Circles")
        Circles.resize(929, 620)
        self.draw_circle_btn = QtWidgets.QPushButton(Circles)
        self.draw_circle_btn.setGeometry(QtCore.QRect(400, 560, 75, 23))
        self.draw_circle_btn.setObjectName("draw_circle_btn")

        self.retranslateUi(Circles)
        QtCore.QMetaObject.connectSlotsByName(Circles)

    def retranslateUi(self, Circles):
        _translate = QtCore.QCoreApplication.translate
        Circles.setWindowTitle(_translate("Circles", "Form"))
        self.draw_circle_btn.setText(_translate("Circles", "Draw circle"))
